#   ===================================
#           OutPutArff
#   ===================================
__author__ = "Simakis Panagiotis"
__license__ = "GPL"
__email__ = "sp1thas@autistici.org"

'''
    me th synarthsh header() dhmiourgoume
    ta label twn xarakthristikw sto
    arxeio arff
'''
#   ===================================
import arff, decodes

def Header():
    '''
    return [ 'SymbolsPerChar',
             'PunctuationsPerChar',
             'SpacesPerChar',
             'UppersPerChar',
             'LettersPerChar',
             'DigitsPerChar',
             'SortWordsPerChar',
             'TotalCharsInWords',
             'AvgWordLength',
             'AvgSentencesPerWord',
             'AvgSentencesPerChar',
             'TotalDifferentWordsPerWords',
             'HapaxLegomenaPerWords',
             'HapaxDislegomenaPerWords',
             'FreqA',
             'FreqB',
             'FreqC',
             'FreqD',
             'FreqE',
             'FreqF',
             'FreqG',
             'FreqH',
             'FreqI',
             'FreqJ',
             'FreqK',
             'FreqL',
             'FreqM',
             'FreqN',
             'FreqO',
             'FreqP',
             'FreqQ',
             'FreqR',
             'FreqS',
             'FreqT',
             'FreqV',
             'FreqU',
             'FreqW',
             'FreqX',
             'FreqY',
             'FreqZ',
             'FreqSmblTilde',
             'FreqSmblAt',
             'FreqSmblHash',
             'FreqSmblDollar',
             'FreqSmblPercent',
             'FreqSmblCaret',
             'FreqSmblAmpersand',
             'FreqSmblAsterisk',
             'FreqSmblDash',
             'FreqSmblDash1',
             'FreqSmblEqulsSign',
             'FreqSmblPlus',
             'FreqSmblGreater',
             'FreqSmblLess',
             'FreqPunctBracket1',
             'FreqPunctBracket2',
             'FreqPunctBracket3',
             'FreqPunctBracket4',
             'FreqPunctVerticalBar',
             'FreqPunctComma',
             'FreqPunctFullStop',
             'FreqPunctQuestionMark',
             'FreqPunctExclamationMark',
             'FreqPunctColon',
             'FreqPunctSemiColon',
             'FreqPunctQuotationMark1',
             'FreqPunctQuotationMark2',
             'MostUsedWrdsUS',
             'MostUsedWrdsUK',
             'MostUsedWrdsAUS',
             'MostUsedWrdsCAN',
             'MostUsedWrdsNNS',
             'FreqWrdsUS',
             'FreqWrdsUK',
             'FreqWrdsAUS',
             'FreqWrdsCAN',
             'class'
            ]'''

    return [
                "BasicFeatures['SymbolsPerChar']",
                "BasicFeatures['PuncuationsPerChar']",
                "BasicFeatures['SpacesPerChar']",
                "BasicFeatures['UpperPerChar']",
                "BasicFeatures['LettersPerChar']",
                "BasicFeatures['DigitsPerChar']",
                "BasicFeatures['ShortWords']",
                "BasicFeatures['TotalCharsInWords']",
                "BasicFeatures['AvgWordLen']",
                "BasicFeatures['AvgSentencesWords']",
                "BasicFeatures['AvgSentencesChars']",
                "BasicFeatures['TotalDiffWords']",
                "BasicFeatures['HapaxLegomena']",
                "BasicFeatures['HapaxDislegomena']",
                "LetterFreq['a']",
                "LetterFreq['b']",
                "LetterFreq['c']",
                "LetterFreq['d']",
                "LetterFreq['e']",
                "LetterFreq['f']",
                "LetterFreq['g']",
                "LetterFreq['h']",
                "LetterFreq['i']",
                "LetterFreq['j']",
                "LetterFreq['k']",
                "LetterFreq['l']",
                "LetterFreq['m']",
                "LetterFreq['n']",
                "LetterFreq['o']",
                "LetterFreq['p']",
                "LetterFreq['q']",
                "LetterFreq['r']",
                "LetterFreq['s']",
                "LetterFreq['t']",
                "LetterFreq['u']",
                "LetterFreq['v']",
                "LetterFreq['w']",
                "LetterFreq['x']",
                "LetterFreq['y']",
                "LetterFreq['z']",
                "SymbolFreq['1']",
                "SymbolFreq['2']",
                "SymbolFreq['3']",
                "SymbolFreq['4']",
                "SymbolFreq['5']",
                "SymbolFreq['6']",
                "SymbolFreq['7']",
                "SymbolFreq['8']",
                "SymbolFreq['9']",
                "SymbolFreq['10']",
                "SymbolFreq['11']",
                "SymbolFreq['12']",
                "SymbolFreq['13']",
                "SymbolFreq['14']",
                "SymbolFreq['15']",
                "SymbolFreq['16']",
                "SymbolFreq['17']",
                "SymbolFreq['18']",
                "SymbolFreq['19']",
                "SymbolFreq['20']",
                "SymbolFreq['21']",
                "PunctuationsFreq['1']",
                "PunctuationsFreq['2']",
                "PunctuationsFreq['3']",
                "PunctuationsFreq['4']",
                "PunctuationsFreq['5']",
                "PunctuationsFreq['6']",
                "PunctuationsFreq['7']",
                "PunctuationsFreq['8']",
                "MostUsedWords['US']",
                "MostUsedWords['UK']",
                "MostUsedWords['AUS']",
                "MostUsedWords['CAN']",
                "MostUsedWords['NNS']",
                "SlanFreq['US']",
                "SlanFreq['UK']",
                "SlanFreq['AUS']",
                "SlanFreq['AUS']",
                "class"
    ]
def Write(header,data):
    print('Eggrafi arxeiou arff')
    DefaultFileName = "resaults.arff"
    print "Default csv file: 'resaults.arff' (Press Enter for default name)"
    FileName = raw_input("Insert arff file name: ") or DefaultFileName #eisagwgh onomatos arxeiou
    return arff.dump("FileName.csv", data, relation='results', names=header)
    del data, header, FileName, DefaultFileName
